version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    build: ./backend
    ports:
      - '5555:5000'
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: '3306'
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: time_db
    restart: always
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
  adminer:
    image: adminer
    ports:
      - '8888:8080'
    restart: always

volumes:
  mysql_data: